### ISSUE TITLE
Consider using TOML for input format for easier interop / simpler codebase

### ISSUE THREAD

**Issue by justinlubin** [justinlubin/honeybee#15]
E.g.

```toml
[[Computation]]
name = "f"
parameters = { x = "A", y = "B" }
returns = "C"
predicate = [
  "x.val < y.val",
  "ret.val < y.val",
  "ret.val = x.val"
]

[[Output]]
name = "Fact"
parameters = { x = "A", y = "B" }
```

and

```toml
[[facts]]
name = "A"
x = 1
y = 2

[[facts]]
name = "Sort"
day = 1

[goal]
name = "Differential Gene Expression"
start = 1
end = 3
```

Or potentially:

```toml
[[facts]]
name = "Sort"
[args]
day = 1
kind = "FACS"
```
